name: staging
url: https://staging.yourdomain.com

# Protection rules for staging environment
protection_rules:
  # Require a pull request before merging
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    
  # Require status checks to pass before merging
  required_status_checks:
    strict: true
    contexts:
      - "CI - Continuous Integration"
      - "lint-and-format"
      - "unit-tests"
      - "e2e-tests"
      - "build-verification"
      
  # Restrict pushes that create files that match the specified glob patterns
  restrictions:
    users: []
    teams: []
    apps: []
    
  # Allow specific actors to bypass the above restrictions
  allowed_actors:
    users: []
    teams: []
    apps: []

# Environment variables for staging
environment_variables:
  NODE_ENV: staging
  AWS_REGION: us-east-1
  STAGING_DOMAIN: staging.yourdomain.com
  
# Deployment branches
deployment_branches:
  - staging
  - develop
  - feature/*
  
# Auto-deploy settings
auto_deploy:
  enabled: true
  branches:
    - staging
  required_checks:
    - "CI - Continuous Integration"
    - "lint-and-format"
    - "unit-tests"
    - "e2E-tests"
